# **1주차 복습과제**
- 1주차 복습과제는 **넘파이/판다스 연습문제**입니다.
- 코드 작성하시고, 출력 결과까지 나오도록 실행 부탁드립니다.
  - 제출 시 파일명 본인 이름으로 변경해 주세요. ex) Week1_복습과제_OOO
- 교재에서 다루지 않은 메소드도 다수 포함되어 있지만 구글링이나 챗지피티 등을 활용해서라도 풀어주세요! 한 번씩 사용해 보면 좋을 것 같아 어려워도 문제에 포함했습니다 🤗

## **넘파이**

### 1. Import the numpy package under the name `np`.

In [70]:
import numpy as np

### 2. Print the numpy version and the configuration.

(hint: `np.__version__`, `np.show_config`)

In [71]:
print('numpy version :',np.__version__)
print('numpy configuration',np.show_config)

numpy version : 2.0.2
numpy configuration <function show at 0x79f9d384a5c0>


### 3. Create a null vector of size 10.

#### ✅ 출력 예시


```
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```



In [72]:
null_v = np.array([0 for i in range(10)])
print(null_v)

[0 0 0 0 0 0 0 0 0 0]


### 4. Create a null vector of size 10 but the fifth value which is 1.

#### ✅출력 예시


```
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
```

In [73]:
null_fif = np.zeros(10)
null_fif[4] = 1
print(null_fif)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 5. Create a vector with values ranging from 10 to 49.

#### ✅출력 예시


```
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
```

In [74]:
vector = np.array([i for i in range(10,50,)])
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 6. Reverse a vector (first element becomes last).

#### ✅출력 예시


```
[9 8 7 6 5 4 3 2 1 0]
```

In [75]:
vector = np.arange(10,0,-1)
print(vector)

[10  9  8  7  6  5  4  3  2  1]


### 7. Create a 3x3 matrix with values ranging from 0 to 8.

#### ✅출력 예시


```
[[0 1 2]
 [3 4 5]
 [6 7 8]]
```

In [76]:
vector = np.arange(0,9)
vector = vector.reshape(3,3)
print(vector)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 8. Find indices of non-zero elements from [1,2,0,0,4,0].

#### ✅출력 예시


```
(array([0, 1, 4]),)
```

In [77]:
vector = np.array([1,2,0,0,4,0])
nonzero_elements= np.nonzero(vector)

print(nonzero_elements)


(array([0, 1, 4]),)


### 9. Create a 3x3 identity matrix.

(hint: `np.eye`)

#### ✅출력 예시


```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

In [78]:
identity_mat = np.eye(3)
print(identity_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 10. Create a 3x3x3 array with random values.

#### ✅출력 예시


```
[[[0.30742852 0.26458726 0.85474383]
  [0.80234531 0.76268902 0.91286677]
  [0.8804109  0.51011378 0.82103555]]

 [[0.403753   0.83120234 0.15202655]
  [0.75782685 0.0732058  0.48148689]
  [0.2089428  0.44968622 0.88134184]]

 [[0.52251191 0.10738374 0.86279648]
  [0.26203911 0.42157754 0.68856833]
  [0.58133626 0.31059127 0.71354172]]]
```

In [79]:
random_array = np.random.random((3,3,3))
print(random_array)

[[[0.93055937 0.66617289 0.28635365]
  [0.78108994 0.42730734 0.43678074]
  [0.18947564 0.77895992 0.21194775]]

 [[0.36288786 0.96649481 0.20598982]
  [0.81713987 0.00914878 0.83535024]
  [0.18276764 0.86943726 0.77923064]]

 [[0.15234325 0.85845761 0.48862997]
  [0.56441771 0.54150836 0.99119292]
  [0.32908868 0.19541972 0.97025123]]]


### 11. Create a 10x10 array with random values and find the minimum and maximum values.

#### ✅출력 예시


```
0.018360924693465508 0.9990506368595156
```

In [80]:
random_array = np.random.random((10,10))
min_val = np.min(random_array)
max_val = np.max(random_array)
print(min_val,max_val)

0.033933683679551074 0.942384980688332


### 12. Create a random vector of size 30 and find the mean value.

#### ✅출력 예시


```
0.46249036320403636
```

In [81]:
random_vector = np.random.random(30)
mean_val = np.mean(random_vector)
print(mean_val)

0.5133719126695072


### 13. Create a 2d array with 1 on the border and 0 inside. (size: 10x10)

#### ✅출력 예시


```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

In [82]:
array = np.zeros((10, 10))

array[0,:] = 1
array[:,0] = 1
array[-1,:] = 1
array[:,-1] = 1

print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 14. How to add a border (filled with 0's) around an existing array?

(hint: 인덱싱 사용)

#### ✅출력 예시


```
# before
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 # after
 [[0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0.]]

```

In [83]:
arr = np.ones((5,5))
print('# before \n',arr)
arr[0,:] = 0
arr[:,0] = 0
arr[-1,:] = 0
arr[:,-1] = 0
print('# after \n',arr)

# before 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
# after 
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 15. What is the result of the following expression?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [84]:
print(0 * np.nan) # nan(Not a Number)이 포함된 연산은 nan이됨
print(np.nan == np.nan) # nan은 자기자신 포함 모든 값과 비교연산자로 비교할 때 false
print(np.inf > np.nan) # nan과 비교연산자로 비교했기 때문에 가장 큰 값임에도 false
print(np.nan - np.nan) # nan이 포함된 연산이기 때문에 nan
print(np.nan in set([np.nan])) # set()은 해시값을 이용해 비교하기 때문에 nan이 들어있을 때 True 반환
print(0.3 == 3 * 0.1) # 부동소수점 오차

nan
False
False
nan
True
False


### 16. Normalize a 5x5 random matrix.

(hint: (x - mean) / std)

#### ✅출력 예시


```
[[-1.4765971   0.9582795  -1.29910242  1.0250981  -0.79801651]
 [ 0.57945383 -1.28559078  0.02733238  0.99675052  1.2702088 ]
 [-0.08513084 -1.4686812  -0.78813593 -0.34559303 -1.15052328]
 [ 0.98183813 -1.41255344  0.37190169  1.05697419 -0.02668639]
 [-1.14466851  0.98911205  1.14499256  0.69454882  1.18478886]]
```

In [85]:
#Normalization는 데이터의 평균을 0, 표준편차를 1로 조정하는 과정
rand_matrix = np.random.rand(5, 5)
m_mean = np.mean(rand_matrix)
m_std = np.std(rand_matrix)
normalized_matrix = (rand_matrix - m_mean) / m_std
print(normalized_matrix)

[[-0.77407141  0.63902911 -0.00854475 -1.62062071  1.80195387]
 [-0.04933067  0.02708822 -1.24966294 -0.49832321  0.08973303]
 [ 0.47513168 -0.3654618   1.4519824  -1.02445885  0.56975675]
 [-0.54302939  0.69765007  1.23606006 -1.7865876   1.57732737]
 [ 0.14899229  0.33727177 -0.57694021  1.10887795 -1.66382301]]


### 17. Multiply a 5x3 matrix by a 3x2 matrix. (real matrix product)

#### ✅출력 예시


```
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
```

In [86]:
A = np.random.randint(0,10,(5, 3))

B = np.random.randint(0,10,(3, 2))

C = np.dot(A, B)
print(C)

[[ 47 102]
 [ 33  85]
 [ 19  51]
 [ 39 108]
 [ 18  63]]


### 18. What are the result of the following expressions?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [87]:
print(np.array(0) / np.array(0)) # 0/0은 수학적으로 정의X > nan 출력
print(np.array(0) // np.array(0)) # 0//0도 수학적으로 정의X > 경고후 0 출력
print(np.array([np.nan]).astype(int).astype(float))
# np.nan.astype(int)는 시스템의 최소정수값으로 변환됨
# 이후 다시 astype(float)로 변환되면서 출력, 경고메세지 발생

nan
0
[-9.22337204e+18]


<ipython-input-87-c0170b688ee0>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0)) # 0/0은 수학적으로 정의X > nan 출력
<ipython-input-87-c0170b688ee0>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0)) # 0//0도 수학적으로 정의X > 경고후 0 출력
<ipython-input-87-c0170b688ee0>:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


### 19. Create a 5x5 matrix with row values ranging from 0 to 4.

#### ✅ 출력 예시

```
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
```

In [88]:
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 20. Create a random vector of size 10 and sort it.

#### ✅출력 예시


```
[0.11443045 0.16715169 0.32515597 0.38374227 0.48327044 0.78728921
 0.80523192 0.85915686 0.96930939 0.99586525]

```

In [89]:
vector = np.random.rand(10)
sorted_vector = np.sort(vector)
print(sorted_vector)

[0.10894661 0.11994176 0.15777656 0.23379369 0.26061087 0.36225265
 0.59663618 0.92937024 0.97234218 0.98548254]


## **판다스**


### 1. Import pandas under the alias `pd`.

In [90]:
import pandas as pd

### 2. Print the version of pandas that has been imported.

In [91]:
print(pd.__version__)

2.2.2


## 3~20번 문제는 아래 데이터프레임으로 진행됩니다.

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```


### 3. Create a DataFrame `df` from this dictionary `data` which has the index `labels`.


In [92]:
# 문제 풀이 전 numpy 임포트
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data,index= labels)
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

### 4. Display a summary of the basic information about this DataFrame and its data.  
(hint: there is a single method that can be called on the DataFrame)

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 700.0+ bytes


### 5. Display a summary of the basic statistics about data of this DataFrame.  
(hint: there is a single method that can be called on the DataFrame)

In [94]:
df.describe()

age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

### 6. Return the first 3 rows of the DataFrame `df`.

In [95]:
df.head(3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

### 7. Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [96]:
df[['animal','age']]

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

### 8. Select the data in rows `[3, 4, 8]` **and** in columns `['animal', 'age']`.

In [97]:
df.iloc[[3, 4, 8], [0, 1]] #컬럼 인덱스 0: animal, 1: age

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

### 9. Select only the rows where the number of visits is greater than 3.

In [98]:
df[df['visits'] > 3]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

### 10. Select the rows where the age is missing, i.e. it is `NaN`.

In [99]:
df[df['age'].isna()]

animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

### 11. Select the rows where the animal is a cat *and* the age is less than 3.

In [100]:
df[(df['animal'] == 'cat') & (df['age'] < 3)]

animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

### 12. Select the rows the age is between 2 and 4 (inclusive).  


In [101]:
df[(df['age'] >= 2) & (df['age'] <= 4) ]

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

### 13. Change the age in row 'f' to 1.5.

In [102]:
df.iloc[5,1] = 1.5
df['age']

a    2.5
b    3.0
c    0.5
d    NaN
e    5.0
f    1.5
g    4.5
h    NaN
i    7.0
j    3.0
Name: age, dtype: float64

### 14. Calculate the sum of all visits in `df` (i.e. the total number of visits).

In [108]:
df = pd.DataFrame(data,index= labels)
total_visits = df['visits'].sum()
print(total_visits)

19


### 15. Calculate the mean age for each different animal in `df`.

In [109]:
df.groupby('animal')['age'].mean()

animal
cat      2.5
dog      5.0
snake    2.5
Name: age, dtype: float64

### 16. Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [110]:
df.loc['k'] = ['elephant', 10, 2, 'yes']
print(df)
df = df.drop('k')

     animal   age  visits priority
a       cat   2.5       1      yes
b       cat   3.0       3      yes
c     snake   0.5       2       no
d       dog   NaN       3      yes
e       dog   5.0       2       no
f       cat   2.0       3       no
g     snake   4.5       1       no
h       cat   NaN       1      yes
i       dog   7.0       2       no
j       dog   3.0       1       no
k  elephant  10.0       2      yes


### 17. Count the number of each type of animal in `df`.

In [111]:
df['animal'].value_counts()

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

### 18. Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).
#### ✅출력 예시

 index |animal	| age	|visits|	priority
---|---|---|---|---
i|	dog|	7.0|	2|	no
e|	dog|	5.0|	2|	no
g|	snake|	4.5|	1|	no
j|	dog|	3.0|	1|	no
b|	cat|	3.0|	3|	yes
a|	cat|	2.5|	1|	yes
f|	cat|	1.5|	3|	no
c|	snake|	0.5|	2|	no
h|	cat|	NaN|	1|	yes
d|	dog|	NaN|	3|	yes

In [112]:
df.sort_values(by=['age', 'visits'], ascending=[False, True])

animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  2.0       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

### 19. The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.  
(hint: `map`)

In [114]:
df['priority'] = df['priority'].map({'yes': True, 'no': False})
df

animal  age  visits priority
a    cat  2.5       1      NaN
b    cat  3.0       3      NaN
c  snake  0.5       2      NaN
d    dog  NaN       3      NaN
e    dog  5.0       2      NaN
f    cat  2.0       3      NaN
g  snake  4.5       1      NaN
h    cat  NaN       1      NaN
i    dog  7.0       2      NaN
j    dog  3.0       1      NaN

### 20. In the 'animal' column, change the 'snake' entries to 'python'.   

In [116]:
df['animal'] = df['animal'].replace('snake', 'python')
df['animal']

a       cat
b       cat
c    python
d       dog
e       dog
f       cat
g    python
h       cat
i       dog
j       dog
Name: animal, dtype: object

In [117]:
# 확인용 df 출력 셀
df

animal  age  visits priority
a     cat  2.5       1      NaN
b     cat  3.0       3      NaN
c  python  0.5       2      NaN
d     dog  NaN       3      NaN
e     dog  5.0       2      NaN
f     cat  2.0       3      NaN
g  python  4.5       1      NaN
h     cat  NaN       1      NaN
i     dog  7.0       2      NaN
j     dog  3.0       1      NaN

### 21. Given a DataFrame of random numeric values:
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # this is a 5x3 DataFrame of float values
```

how do you subtract the row mean from each element in the row?

In [118]:
# 랜덤 시드 고정
np.random.seed(2025)

df = pd.DataFrame(np.random.random(size=(5, 3)))

# 각 행에서 행 평균을 빼기
df_normalized = df.sub(df.mean(axis=1), axis=0)

print(df_normalized)


          0         1         2
0 -0.516494  0.235870  0.280624
1  0.081768  0.024435 -0.106204
2 -0.047373 -0.212124  0.259497
3  0.115235 -0.230544  0.115309
4 -0.229731  0.498009 -0.268278
